language: python

sudo: false

python:
  - "3.6"

env:
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=master

addons:
  postgresql: '9.5'

matrix:
  include:
    - { python: "3.6", env: TOXENV=flake8 }

  allow_failures:
    - env: DJANGO=master

install:
    - pip install tox-travis

before_script:
  - psql -c 'CREATE DATABASE dynamic_initial_data;' -U postgres

script:
    - tox

after_success:
  coveralls

notifications:
    email: false
