sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.9,<1.10"
    - DJANGO=">=1.10,<1.11"
    - DJANGO=">=1.11,<2.0"
    - DJANGO=">=2.0,<2.1"
matrix:
  exclude:
  - python: 2.7
    env: DJANGO=">=2.0,<2.1"
install:
  - pip install -q coverage flake8 Django$DJANGO django-nose>=1.4
before_script:
  - flake8 .
  - psql -c 'CREATE DATABASE dynamic_initial_data;' -U postgres
script:
  - coverage run setup.py test
  - coverage report --fail-under=100
